version: "3.9"

services:
  sportschool-exam:
    container_name: sportschool-exam
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # external:internal
      - "5446:5432"
    volumes:
      - sportschool_dist-db-sportsystem-volume:/var/lib/postgresql/data

volumes:
  sportschool_dist-db-sportsystem-volume:
